export const GET_MOVIE_INFO = 'GET_MOVIE_INFO'
export const SEARCH_MOVIES_BY_TERM = 'SEARCH_MOVIES_BY_TERM'
export const SEARCH_MOVIES_BY_PAGE = 'SEARCH_MOVIES_BY_PAGE'

export const GET_FAVORITES_MOVIES = 'GET_FAVORITES_MOVIES'
export const ADD_FAVORITE_MOVIE = 'ADD_FAVORITE_MOVIE'
export const REMOVE_FAVORITE_MOVIE = 'REMOVE_FAVORITE_MOVIE'
